### ISSUE TITLE
[第27天] 怎样修改 chrome 记住密码后自动填充表单的黄色背景？

### ISSUE THREAD

**Issue by Renato-Z** [Renato-Z/exercises#100]
表单的样式是谷歌浏览器内置的，并且加了`!important`，样式无法覆盖

可以使用内阴影的方式
```css
input{
    &:-webkit-autofill {
      box-shadow: 0 0 0px 1000px rgba(255, 255, 255, 0) inset !important;
      -webkit-text-fill-color: #000 !important;
      transition: background-color 5000s ease-in-out 0s;
      font-size: 14px;

    }
  }
```
