### ISSUE TITLE
[第6天] 用 css 创建一个三角形，并简述原理

### ISSUE THREAD

**Issue by Renato-Z** [Renato-Z/exercises#17]
## 使用 border 方法

```html
<div class="box"></div>
```

`CSS代码`

```css
.box {
  width: 0;
  height: 0;
  border-right: 100px transparent solid;
  border-bottom: 100px blue solid;
}
```

关于原理说不清楚，没有找到详细说明的文章，简单理解就是，木匠在做相框的时候，也会把每条框的边做成 45 度，方便贴合

## 另外一种，transform

使用旋转、倾斜等方法做出三角形
