### ISSUE TITLE
[第 8 天] 清除浮动的方式有哪些及优缺点？

### ISSUE THREAD

**Issue by Renato-Z** [Renato-Z/exercises#23]
## 浮动造成的问题

- 浮动的元素脱离了标准流，并且触发了 BFC，所以当前的盒子与外部和盒子布局互不影响，所以导致浮动的元素可能会盖住其他的盒子

### 1. 给浮动的元素下面添加一个带 clear 属性的空盒子

可以是 div 也可以是其它块级元素，把 <div style="clear:both;"></div>放在盒内底部，用最下面的空盒子清除浮动，把盒子重新撑起来。

```html
<div style="clear:both;"></div>
```

**缺点**：使用过多会让页面中多出很多无意义的盒子

### 2. 使用 overflow: hidden

给浮动元素的`父元素`添加 overflow: hidden 样式，原理是让父元素触发 BFC，可以计算浮动元素的高度

**缺点**：会导致溢出的元素被隐藏，可能影响展示效果

### 3. 给父元素固定宽高

给父元素固定宽高，就可以计算父盒子的宽高

### 4. 使用 after 伪元素清除浮动

给外部盒子的 after 伪元素设置 clear 属性，再隐藏它
这也是最好用的办法之一

```css
.clearfix {
  *zoom: 1;
}
.clearfix:before,
.clearfix:after {
  display: table;
  line-height: 0;
  content: "";
}
.clearfix:after {
  clear: both;
}
```
