### ISSUE TITLE
[第14天] position:fixed;在 ios 下无效该怎么办？

### ISSUE THREAD

**Issue by Renato-Z** [Renato-Z/exercises#43]
在做一些吸顶、吸底效果时，一般会使用 position: fixed;来达到效果，但是这个属性在 ios 中有时会失效

## 解决办法

把吸顶吸底的盒子独立于要滑动的内容之外

这个是要滑动的内容的 css：

```css
.content {
  overflow: auto;
  /* 增加滑动流畅度 */
  -webkit-overflow-scrolling: touch;
  box-sizing: border-box;
  height: 100%;
  position: relative;
  z-index: 1;
}
```

这个是底部的盒子

```css
.scroll-page {
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 50px;
}
```
