### ISSUE TITLE
[第22天] 说说浏览器解析 CSS 选择器的过程？

### ISSUE THREAD

**Issue by Renato-Z** [Renato-Z/exercises#80]
## 解析 CSS 选择器的过程
是从右向左的

原因很简单，比如这个例子：
```css
.container span a {
    color: red;
}
```

如果是从左向右，首先container，可能有n个span，要遍历每一个span，没有a标签，则遍历下一个span，会有大量的无用遍历

正确的是：从右向左。首先寻找到所有的a，但是a的父级不会全是span，筛选凋一部分，span父级也不全是container，这样性能更好，效率更快

参考：https://blog.csdn.net/scusyq/article/details/7059063
参考：https://juejin.im/entry/5a123c55f265da432240cc90#comment
